### ISSUE TITLE
fails to write the backup dbf in Windows 7

### ISSUE THREAD

**Issue by watkec** [borysiasty/tablemanager#4]
Using the Table Manager with QGIS 2.10.1 on a Windows 7 machine.  After reordering the attributes the plugin fails to save or save as and all edits are lost.

Seems to be working on Ubuntu 14.04 but not in Windows 7.

**Comment by borysiasty** [comment]
Thank you @watkec for the report. Please note we have now much more robust tool in the Processing toolbox, so currently I don't have any plans to release further TableManager updates. It was designed as a workaround while there wasn't any native tool.

You can find it in *Advanced interface* mode, under *QGIS Geoalgorithms -> Vector table tools -> Refactor fields*

**Comment by watkec** [comment]
Thanks for your reply -- I did not see the Advanced interface mode
before.  I can see how to REORDER THE FIELDS suing the Refactor fields
under Vector table tools.  However, I can not figure out how to RENAME
THE FIELD -- AT HEAD OF COLUMN.

I do not see where that can be done.  Do you know a work around for
renaming the fields?

Thanks.



On 09/13/2015 07:47 AM, Borys Jurgiel wrote:
>
> Thank you @watkec <https://github.com/watkec> for the report. Please
> note we have now much more robust tool in the Processing toolbox, so
> currently I don't have any plans to release further TableManager
> updates. It was designed as a workaround while there wasn't any native
> tool.
>
> You can find it in /Advanced interface/ mode, under /QGIS
> Geoalgorithms -> Vector table tools -> Refactor fields/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borysiasty/tablemanager/issues/4#issuecomment-139863280>.
>

-- 

===================================
Curt Watke, PhD
Slavnik Labs Analytics
Envisioning Cultural Distinctions

**Comment by borysiasty** [comment]
@watkec - doubleclick on the name (also works with all other table cells). It's not very intuitive, I admit!

**Comment by borysiasty** [comment]
I'm closing the issue as Table Manager is now obsolete and superseded by the Refactor Fields algorithm.
